### ISSUE TITLE
Change of Steering Group representative for Microsoft

### ISSUE THREAD

**Issue by diekus** [w3c/whatwg-coord#21]
Hola,

Creating this issue to notify the group of a change to the SG representative for Microsoft to myself, [Diego González](https://github.com/diekus) as per previous approvals and discussions in both Slack and email.

**Comment by sideshowbarker** [comment]
Howdy Diego — thanks for the heads-up, and super glad to know it’s you who’s taken on the WHATWG SG responsibilities for Microsoft. Now that we’ve had this open for a while and people have had a chance to see it, I’m going ahead and closing it since I think there’s no further action we need to take on it
