### ISSUE TITLE
Moving Media Playback Quality

### ISSUE THREAD

**Issue by plehegar** [w3c/whatwg-coord#8]
- ~~[x] Waiting on Media WG to publish a CR?~~
- [ ] WHATWG published as part of HTML
- ~~[ ] W3C retires the WD or CR and do the /TR redirect to /TR/html~~

**Comment by tidoust** [comment]
> Waiting on Media WG to publish a CR?

The spec has not been published on /TR at all but it used to be part of the Media Source Extensions CR (as a feature at risk that got removed before publication as PR). The Media WG does not plan to publish the spec to /TR before it gets integrated into HTML.

**Comment by foolip** [comment]
The existing spec for this is https://w3c.github.io/media-playback-quality/.

**Comment by sideshowbarker** [comment]
Closing this as nothing needed to do, per previous comments

**Comment by annevk** [comment]
Well, we haven't completed the bullet points in OP I think, so we should keep this open until we can tick those off.

**Comment by sideshowbarker** [comment]
Per previous comments, we don't need to do "W3C retires the WD or CR and do the /TR redirect to /TR/html", right?

And if so, that means that the only thing left is that WHATWG still needs to do "WHATWG published as part of HTML"?

And if so, does WHATWG actually plan on ever doing that? Is there an open issue for it in the HTML issue tracker?

**Comment by annevk** [comment]
I think that's correct. I don't know what the timeline is or if there is an issue (suspect not?), but it does seem like something that needs to happen eventually.

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/whatwg/html/issues/9489, so I’m now going ahead and closing this. But @annevk if you still see any need to keep this issue open, then please feel free to re-open it.

But to be clear: This issue was originally added to this tracker based on the understanding that we’d have something published in TR spec for this. But since we never did publish anything for this in TR — and since this tracker is in practice for issues for things that have impact on formal W3C process requirements outlined in the W3C Process doc (e.g., retiring specs published in TR), there’s nothing else we need to track here with regard to WHATWG-W3C coordination.

We will eventually need to redirect https://w3c.github.io/media-playback-quality/ to the relevant part of HTML — but doing that doesn’t touch on W3C process requirements in any way; instead I can just handle it on my own once the time comes.
